version: '3.9'

services:
  postgres_db:
    image: postgres
    command: -c 'max_connections=200'
    container_name: restaurant_db
    ports:
      - '5440:5432'
    environment:
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: denis123
      POSTGRES_DB: restaurant-database
    volumes:
      - './pgdata:/var/lib/postgresql/data'
      - './utils/init.sql:/docker-entrypoint-initdb.d/init.sql'
volumes:
  postgres_db: